server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.44.184:3306/micro_campus?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource #druid监控配置
    filters: stat,wall
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    dbcp2:
      min-idle: 5 #数据库链接池最小维持连接数
      max-total: 10  #最大的链接数
      initial-size: 5 #初始化提供的连接数
      max-wait-millis: 200 #等待链接获取的最大超时时间
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    open-in-view: false
#解决org.hibernate.LazyInitializationException: could not initialize proxy - no Session报错-懒加载问题
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
##        generate_statistics: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        #show-sql : true #打印sql
        format_sql: true #格式化sql
#        use_sql_comments: true #指出是什么操作生成了该语句
        enable_lazy_load_no_trans: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML
    cache: false
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: 47.98.44.184 #Redis服务器地址，请替换为自己的redis服务器地址
    port: 6379 #Redis服务器连接端口
    #password:  # Redis服务器连接密码（默认为空）
  servlet:
    multipart:
      max-file-size: 31457280
      max-request-size: 31457280
swagger2:
  enable: true
#微信身份认证
wechat:
  appid: wxaea6a8e1cbdc644b
  appsecret: a66479d55904ecadd24b4b2ae5b7d14a
logging:
  file: log/score-inquiry.log




